### ISSUE TITLE
Is it working yet on Android?

### ISSUE THREAD

**Issue by tdurand** [macdonst/SpeechRecognitionPlugin#1]
Hello, i was wondering if it was working ? close to work ? 

(The README clearly says that it doesn't work, but maybe it's close to work ;-))

Thanks

**Comment by moisesd37** [comment]
has anyone achieved something with this plugin? could you provide something that could help? i've found nothing.

**Comment by jcesarmobile** [comment]
I've just tested a simple example and worked on both iOS and android
The example is example 1 from 6.1 Speech Recognition Examples (https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html)

 <script type="text/javascript">
    var recognition = new SpeechRecognition();
    recognition.onresult = function(event) {
      if (event.results.length > 0) {
        q.value = event.results[0][0].transcript;
        q.form.submit();
      }
    }
  </script>

  <form action="http://www.example.com/search">
    <input type="search" id="q" name="q" size=60>
    <input type="button" value="Click to Speak" onclick="recognition.start()">
  </form>

**Comment by Danyzzz** [comment]
I copy this code in my index, but my cordova app not work...in my index there is only this code.
When I press "click to speak" speech recognizer not start.

**Comment by jcesarmobile** [comment]
did you link the cordova.js?

**Comment by Danyzzz** [comment]
yes! it is possible paste a complete index?

**Comment by jcesarmobile** [comment]
You are probabli calling the new SpeechRecognition before the device ready, do something like this:

var 
document.addEventListener('deviceready', onDeviceReady, false);

**Comment by moisesd37** [comment]
Thank God! and thank you jcesar, i did it!. Another question jcesar (out of the topic) your native language is not english, what is it?

**Comment by jcesarmobile** [comment]
lol, is it that obvious? my mother tongue is spanish

**Comment by moisesd37** [comment]
yes, it is. mine too, that´s why i noticed. I'm from Colombia, what about you?

**Comment by Danyzzz** [comment]
jcesarmobile thank you for share the code! now run perfect :) there is a solution for work the example 3 from section 6.1? Continuous speech recognition.
Speech Recognition Examples of the W3C page (https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html#examples)

**Comment by jcesarmobile** [comment]
@moisesd37 I'm from Spain

@Danyzzz I didn't try the continuous speech recognition on android, on iOS it won't work yet, it might be possible to do so, but I use iSpeech SDK for the speech recognition, and it works sending the audio to iSpeech servers, continuous speech recognition might take a lot of time to get the result and a lot of data transfer, and it wont recognize anything until you stop the listening or the SDK detects a silence (if configured to do so, and you'll have to restart it after it stops)

**Comment by Danyzzz** [comment]
I tried the example 3 but do not know how to make it work and I do not know if you can do it ! you can work on this ? could become the best plugins for listening voice!

**Comment by dgerding** [comment]
Hi all, not sure if this helps, but I have it running now on Android using Telerik AppBuilder (Cordova).  Check out my short "thread" under the closed issues to see the change I made to the config.xml to get the plugin working and recognized.  Running cordova 3.7 on an android 5.1.

**Comment by Selvam75** [comment]
I have installed the plugin which gives following error when adding the plugin,Thanks in advance for help,

 Failed to install 'org.apache.cordova.speech.speechrecognition':Failed to fetch plugin cordova-plugin-compat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: SELF_SIGNED_CERT_IN_CHAIN
    at registry.fetch.fail.then.pinfo (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:146:33)
    at _rejected (/usr/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)
Error: Failed to fetch plugin cordova-plugin-compat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: SELF_SIGNED_CERT_IN_CHAIN
